apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  namespace: bigdata-pipeline
spec:
  serviceName: hdfs-datanode
  replicas: 2 # <---  Để 1 node chạy test trước, máy khỏe thì sửa thành 2, 3
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
        - name: datanode
          image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
          env:
            # SỬA 1: Trỏ đúng vào Service của Namenode (giả sử tên service là hdfs-namenode)
            - name: SERVICE_PRECONDITION
              value: "hdfs-namenode:9870"
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://hdfs-namenode:9000"
            
            # Cấu hình chuẩn cho permission
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            
            # Bổ sung: Giúp tránh lỗi permission khi mount volume trên local
            - name: HDFS_CONF_dfs_datanode_data_dir_perm
              value: "700" 
          #gắn ổ cứng vào Container
          volumeMounts:
            - name: datanode-data
              mountPath: /hadoop/dfs/data

          resources:
            requests:
              memory: "256Mi" # Tăng nhẹ request để khởi động ổn định hơn
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 9864
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 9864
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: datanode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi # Tăng lên 5GB để thoải mái test data
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  namespace: bigdata-pipeline
spec:
  type: ClusterIP
  clusterIP: None # Headless service cho StatefulSet
  selector:
    app: hdfs-datanode
  ports:
    - port: 9864
      targetPort: 9864
      name: http
    - port: 9866
      targetPort: 9866
      name: ipc
    - port: 9867
      targetPort: 9867
      name: stream