apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  namespace: bigdata-pipeline
spec:
  serviceName: namenode
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870
              name: web
            - containerPort: 9000
              name: rpc
          env:
            - name: CLUSTER_NAME
              value: "test"
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://namenode:9000"
            - name: CORE_CONF_hadoop_http_staticuser_user
              value: "root"
            - name: HDFS_CONF_dfs_webhdfs_enabled
              value: "true"
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9870
            initialDelaySeconds: 30
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: namenode-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: bigdata-pipeline
spec:
  type: ClusterIP
  selector:
    app: namenode
  ports:
    - port: 9870
      targetPort: 9870
      name: web
    - port: 9000
      targetPort: 9000
      name: rpc