apiVersion: v1
kind: Namespace
metadata:
  name: bigdata-pipeline

---
# Zookeeper StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: bigdata-pipeline
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.1.0
          ports:
            - containerPort: 2181
              name: client
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
# Zookeeper Service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: bigdata-pipeline
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      name: client
---
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
  namespace: bigdata-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.1.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-1:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"
          volumeMounts:
            - name: kafka-1-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-1-data
          emptyDir: {}   
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: bigdata-pipeline
spec:
  selector:
    app: kafka-1
  ports:
    - port: 9092
      targetPort: 9092
      name: broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2
  namespace: bigdata-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.1.0
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-2:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"
          volumeMounts:
            - name: kafka-2-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-2-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: bigdata-pipeline
spec:
  selector:
    app: kafka-2
  ports:
    - port: 9093
      targetPort: 9093
      name: broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-3
  namespace: bigdata-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
        app: kafka-3
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.1.0
          ports:
            - containerPort: 9094
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-3:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"
          volumeMounts:
            - name: kafka-3-data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-3-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  namespace: bigdata-pipeline
spec:
  selector:
    app: kafka-3
  ports:
    - port: 9094
      targetPort: 9094
      name: broker
---

apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: bigdata-pipeline
spec:
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
      name: cql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: bigdata-pipeline
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:latest
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra
          ports:
            - containerPort: 9042
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
